CREATE TABLE posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created DATETIME NOT NULL,
  slug VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  excerpt MEDIUMTEXT NOT NULL,
  content MEDIUMTEXT NOT NULL,

  UNIQUE (slug)
);
